// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_kfe
int cpp_kfe(NumericVector& pdf_u, NumericVector& pdf_l, NumericVector& xx, const int nt, const int nx, const double dt, const double dx, double sigma, const NumericVector b_vals, const NumericVector mu_vals, const NumericVector dt_b_vals);
RcppExport SEXP _dRiftDM_cpp_kfe(SEXP pdf_uSEXP, SEXP pdf_lSEXP, SEXP xxSEXP, SEXP ntSEXP, SEXP nxSEXP, SEXP dtSEXP, SEXP dxSEXP, SEXP sigmaSEXP, SEXP b_valsSEXP, SEXP mu_valsSEXP, SEXP dt_b_valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type pdf_u(pdf_uSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type pdf_l(pdf_lSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type xx(xxSEXP);
    Rcpp::traits::input_parameter< const int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< const int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< const double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< const double >::type dx(dxSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type b_vals(b_valsSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu_vals(mu_valsSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type dt_b_vals(dt_b_valsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kfe(pdf_u, pdf_l, xx, nt, nx, dt, dx, sigma, b_vals, mu_vals, dt_b_vals));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dRiftDM_cpp_kfe", (DL_FUNC) &_dRiftDM_cpp_kfe, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_dRiftDM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
