// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_imzero
int cpp_imzero(NumericVector& pdf_u, NumericVector& pdf_l, const int nt, const double dt, const double sigma, const NumericVector& b_vals, const NumericVector& mu_vals, const NumericVector& mu_int_vals, const NumericVector& dt_b_vals, const NumericVector& t_vec);
RcppExport SEXP _dRiftDM_cpp_imzero(SEXP pdf_uSEXP, SEXP pdf_lSEXP, SEXP ntSEXP, SEXP dtSEXP, SEXP sigmaSEXP, SEXP b_valsSEXP, SEXP mu_valsSEXP, SEXP mu_int_valsSEXP, SEXP dt_b_valsSEXP, SEXP t_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type pdf_u(pdf_uSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type pdf_l(pdf_lSEXP);
    Rcpp::traits::input_parameter< const int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< const double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type b_vals(b_valsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mu_vals(mu_valsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mu_int_vals(mu_int_valsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type dt_b_vals(dt_b_valsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type t_vec(t_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_imzero(pdf_u, pdf_l, nt, dt, sigma, b_vals, mu_vals, mu_int_vals, dt_b_vals, t_vec));
    return rcpp_result_gen;
END_RCPP
}
// cpp_kfe_ada
int cpp_kfe_ada(NumericVector& pdf_u, NumericVector& pdf_l, NumericVector& xx, const int nt, const int nx, const double dtbase, const double dx, const double sigma, const NumericVector& b_vals, const NumericVector& mu_vals, const NumericVector& dt_b_vals, const NumericVector& x_vec);
RcppExport SEXP _dRiftDM_cpp_kfe_ada(SEXP pdf_uSEXP, SEXP pdf_lSEXP, SEXP xxSEXP, SEXP ntSEXP, SEXP nxSEXP, SEXP dtbaseSEXP, SEXP dxSEXP, SEXP sigmaSEXP, SEXP b_valsSEXP, SEXP mu_valsSEXP, SEXP dt_b_valsSEXP, SEXP x_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type pdf_u(pdf_uSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type pdf_l(pdf_lSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type xx(xxSEXP);
    Rcpp::traits::input_parameter< const int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< const int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< const double >::type dtbase(dtbaseSEXP);
    Rcpp::traits::input_parameter< const double >::type dx(dxSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type b_vals(b_valsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mu_vals(mu_valsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type dt_b_vals(dt_b_valsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x_vec(x_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kfe_ada(pdf_u, pdf_l, xx, nt, nx, dtbase, dx, sigma, b_vals, mu_vals, dt_b_vals, x_vec));
    return rcpp_result_gen;
END_RCPP
}
// cpp_kfe_ada_fixed_mu_b
int cpp_kfe_ada_fixed_mu_b(NumericVector& pdf_u, NumericVector& pdf_l, NumericVector& xx, const int nt, const int nx, const double dtbase, const double dx, const double sigma, const double b_val, const double mu_val, const NumericVector& x_vec);
RcppExport SEXP _dRiftDM_cpp_kfe_ada_fixed_mu_b(SEXP pdf_uSEXP, SEXP pdf_lSEXP, SEXP xxSEXP, SEXP ntSEXP, SEXP nxSEXP, SEXP dtbaseSEXP, SEXP dxSEXP, SEXP sigmaSEXP, SEXP b_valSEXP, SEXP mu_valSEXP, SEXP x_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector& >::type pdf_u(pdf_uSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type pdf_l(pdf_lSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type xx(xxSEXP);
    Rcpp::traits::input_parameter< const int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< const int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< const double >::type dtbase(dtbaseSEXP);
    Rcpp::traits::input_parameter< const double >::type dx(dxSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type b_val(b_valSEXP);
    Rcpp::traits::input_parameter< const double >::type mu_val(mu_valSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x_vec(x_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kfe_ada_fixed_mu_b(pdf_u, pdf_l, xx, nt, nx, dtbase, dx, sigma, b_val, mu_val, x_vec));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dRiftDM_cpp_imzero", (DL_FUNC) &_dRiftDM_cpp_imzero, 10},
    {"_dRiftDM_cpp_kfe_ada", (DL_FUNC) &_dRiftDM_cpp_kfe_ada, 12},
    {"_dRiftDM_cpp_kfe_ada_fixed_mu_b", (DL_FUNC) &_dRiftDM_cpp_kfe_ada_fixed_mu_b, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_dRiftDM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
