# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_imzero <- function(pdf_u, pdf_l, nt, dt, sigma, b_vals, mu_vals, mu_int_vals, dt_b_vals, t_vec) {
    .Call(`_dRiftDM_cpp_imzero`, pdf_u, pdf_l, nt, dt, sigma, b_vals, mu_vals, mu_int_vals, dt_b_vals, t_vec)
}

cpp_kfe_ada <- function(pdf_u, pdf_l, xx, nt, nx, dtbase, dx, sigma, b_vals, mu_vals, dt_b_vals, x_vec) {
    .Call(`_dRiftDM_cpp_kfe_ada`, pdf_u, pdf_l, xx, nt, nx, dtbase, dx, sigma, b_vals, mu_vals, dt_b_vals, x_vec)
}

cpp_kfe_ada_fixed_mu_b <- function(pdf_u, pdf_l, xx, nt, nx, dtbase, dx, sigma, b_val, mu_val, x_vec) {
    .Call(`_dRiftDM_cpp_kfe_ada_fixed_mu_b`, pdf_u, pdf_l, xx, nt, nx, dtbase, dx, sigma, b_val, mu_val, x_vec)
}

